### ISSUE TITLE
Errors with goconfig library when trying to run app

### ISSUE THREAD

**Issue by jjhatobjective** [chenzhe07/portproxy#2]
Replicated on go version go1.13.4 linux/amd64 and go version go1.14.2 linux/amd64

Getting an issue with the goconfig library when I trry to run this app, looks like its trying to init an input which dosent exist, is there a config file I should be adding ? I did notice there is a conf flag in main.go since the initial commit however I cant work out why this error is happening. 

The port is free and the sql server is resolvable / reachable. 

```
./portproxy backend="server.address.net:3306" -bind="33075" -buffer=4096 -daemon=false -logTo="stdout"

2020/04/23 04:32:40 Can't get config info, skip insert log to mysql...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ebe96]

goroutine 1 [running]:
github.com/arstercz/goconfig.(*ConfigFile).GetRawString(0x0, 0x6b41c0, 0x7, 0x6b3969, 0x3, 0x605f7a, 0x0, 0x0, 0xc000093f90)
        /root/go/src/github.com/arstercz/goconfig/configfile.go:427 +0x96
github.com/arstercz/goconfig.(*ConfigFile).GetString(0x0, 0x6b41c0, 0x7, 0x6b3969, 0x3, 0x0, 0x30, 0x6b3ce4, 0xc000093e98)
        /root/go/src/github.com/arstercz/goconfig/configfile.go:448 +0x74
main.get_backend_dsn(...)
        /root/go/src/github.com/arstercz/portproxy/conf.go:17
main.main()
        /root/go/src/github.com/arstercz/portproxy/main.go:66 +0x4b9

```

**Comment by arstercz** [comment]
hi @jjhatobjective , the `portproxy` which you used will insert the `sql query` to the [conf.backend](https://github.com/arstercz/portproxy/blob/master/conf.cnf), you should  import the table [query_log](https://github.com/arstercz/portproxy/blob/master/test.sql) to your  database that record the sql query.

**note**: portproxy only used in test environments.

**Comment by arstercz** [comment]
@jjhatobjective , you can test with the latest version. I have skip error when the `conf` option is not set.

**Comment by jjhatobjective** [comment]
That is able to start the proxy now however it looks like the flags arent being read by the application and the defaults are being used in place 

```
[root@dev-server ~]# ./portproxy backend=mysql.server.net:3306 -bind="8003" -buffer=4096 -daemon=false -logTo=stdout                                                                   
2020/04/23 23:06:57 Can't get config info, skip insert log to mysql...
2020/04/23 23:06:57 portproxy started.
2020/04/23 23:07:46 client: 127.0.0.1:47488 ==> 127.0.0.1:8002
2020/04/23 23:07:46 dial tcp 127.0.0.1:8003: connect: connection refused
```

I did some experimenting with a pointer instead of a StringVar but still the flag inpput is not being parsed, Changing the default value works however. 

```
	//flag.StringVar(&bind, "bind", ":8002", "locate ip and port")
	BindPtr := flag.String("bind", ":8003", "locate ip and port"


	p := New(*BindPtr, backend, uint32(buffer))
	log.Println("portproxy started.")
	go p.Start()
	waitSignal()
```


```
tcp6       0      0 :::8003                 :::*                    LISTEN      25763/portproxy
```
I havent seen this before, it appears to not be accepting cli flags :/

**Comment by jjhatobjective** [comment]
@arstercz  nevermind I was missing a - on my backend flag, everything is working now, thanks  for your help.
